version: '3.8'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # Change auth method from scram-sha-256 to md5 because the error occurs in libpq on Apple M1
#      POSTGRES_INITDB_ARGS: --auth-host=md5
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgres/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    expose:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
#      MINIO_ACCESS_KEY: admin
#      MINIO_SECRET_KEY: adminadmin
    hostname: minio
    volumes:
      - data:/var/lib/minio/data
#  nginx:
#    image: nginx:1.19.2-alpine
#    hostname: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    depends_on:
#      - minio


volumes:
  pg-data:
  data:
