# Generated by Django 3.2 on 2022-05-28 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('desc', models.TextField()),
                ('download_counter', models.PositiveBigIntegerField(default=0)),
                ('version', models.CharField(default='0.0.1', max_length=16)),
                ('apkfile', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['-download_counter'],
            },
        ),
        migrations.CreateModel(
            name='AppAgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('desc', models.CharField(max_length=500)),
                ('min_age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=3000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appkind')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='age_limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appagelimit'),
        ),
        migrations.AddField(
            model_name='app',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.devaccount'),
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ManyToManyField(blank=True, to='app.AppCategory'),
        ),
        migrations.AddField(
            model_name='app',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appkind'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(rate__range=(1, 5)), name='valid_rate'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'app'), name='rated_once'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('app', 'user'), name='commented_once'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='createds_once'),
        ),
    ]
